package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
import <%= appPackage %>.<%= packageName %>.<%= name %>;

import android.os.Bundle;
import android.support.annotation.Nullable;

/**
 * Generated by generator-android-template
 */
public class <%= name %>VM extends FragmentBaseVM<<%= name %>, <%= name %>Binding> {

  private static final String TAG = <%= name %>VM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public <%= name %>VM(<%= name %> fragment, <%= name %>Binding binding,@Nullable Bundle savedInstance) {
       super(fragment, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
