package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.activity.ActivityBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;

import com.joxad.androidtemplate.core.adapter.GenericFragmentAdapter;
import com.joxad.androidtemplate.core.fragment.FragmentTab;
import java.util.List;
import java.util.ArrayList;

/**
 * Generated by generator-android-template
 * This class is an activity with a bottom bar navigation that will handle the change of fragment using :
 * - GenericFragmentAdapter using FragmentTab (Name, Fragment)
 * - Navigation on the tabs
 * You can generate your fragment using : yo android-template:fragment/yo android-template:fragment-support
 */
public class <%= name %>VM extends ActivityBaseVM<<%= name %>, <%= name %>Binding> {

  private static final String TAG = <%= name %>VM.class.getSimpleName();

  /***
    * @param activity
    * @param binding
    */
   public <%= name %>VM(<%= name %> activity, <%= name %>Binding binding) {
       super(activity, binding);
   }

   @Override
   public void onCreate() {
     GenericFragmentAdapter fragmentAdapter = new GenericFragmentAdapter(activity, activity.getSupportFragmentManager()) {
               @Override
               public List<FragmentTab> tabTitles() {
                   return tabs();
               }
           };

           binding.viewPager.setAdapter(fragmentAdapter);

           binding.bottomNavigation.setOnNavigationItemSelectedListener(item -> {
               int position = 0;
               switch (item.getItemId()) {
                   case R.id.bottom_navigation_menu_1:
                       position = 0;
                       break;
                   case R.id.bottom_navigation_menu_2:
                       position = 1;
                       break;
                   case R.id.bottom_navigation_menu_3:
                       position = 2;
                       break;
               }
               binding.viewPager.setCurrentItem(position, true);
               return true;
           });
       }

      /***
      * Add your list of tabs here
      * For example
      private List<FragmentTab> tabs() {
        return Arrays.asList(
                new FragmentTab("Dashboard", FragmentDashboard.newInstance()),
                new FragmentTab("Edition", FragmentEditPage.newInstance()),
                new FragmentTab("My top menus", FragmentMenus.newInstance())

        );
    }
      */
       private List<FragmentTab> tabs() {
           return new ArrayList<>();
       }

}
