package <%= appPackage %>.<%= packageName %>;

import com.joxad.androidtemplate.core.ws.RetrofitBase;
import <%= appPackage %>.<%= packageName %>.endpoint.ScheduleEndpoint;

/**
 * Generated by generator-android-template
 *
 * You can create custom init using a custom gson converter and adding an interceptor
 */
public enum <%= dataName %>Manager {
    INSTANCE;

    <%= dataName %>Endpoint endpoint;

    public void init(final String url) {
       this.init(url, null, null);
   }

   public void init(final String url, @Nullable Interceptor interceptor) {
       this.init(url, interceptor, null);
   }

   public void init(final String url, @Nullable Gson gson) {
       this.init(url, null, gson);
   }

   public void init(final String url, @Nullable Interceptor interceptor, @Nullable Gson gson) {
       endpoint = new RetrofitBase(url, interceptor, gson).create(<%= dataName %>Endpoint.class);
   }




}
