package <%= appPackage %>.<%= packageName %>.db;

import io.realm.RealmObject;

/**
 * Generated by generator-android-template
 * This is the realm class of <%= dataClass %>.
 * This is stored in the DB using Realm . You can access them using you <%= dataClass %>Manager
 */
public class <%= dataClass %>DTO extends RealmObject {
  public String id;

  public <%= dataClass %>() {

  }
}
