package <%= appPackage %>.<%= packageName %>.pojo;

/**
 * Generated by generator-android-template
 * This is the pojo class you got by using <%= dataClass %>Endpoint.
 * This will be stored in the DB using Realm as a Realm<%= dataClass %>
 */
public class <%= dataClass %> {

  public <%= dataClass %>() {
    
  }
}
