package com.fragment.test;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.fragment.test.R;
import com.fragment.test.BR;
import com.fragment.test.databinding.FrgmentHomeBinding;
import com.fragment.test.fragment.FrgmentHome;

/**
 * Generated by generator-android-template
 */
public class FrgmentHomeVM extends FragmentBaseVM<FrgmentHome, FrgmentHomeBinding> {
  /***
    * @param fragment
    * @param binding
    */
   public FrgmentHomeVM(FrgmentHome fragment, FrgmentHomeBinding binding) {
       super(fragment, binding);
   }

   @Override
   public void onCreate() {

   }
}
