package com.fragment.test;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.fragment.test.R;
import com.fragment.test.BR;
import com.fragment.test.fragment.FrgmentHomeVM;
import com.fragment.test.databinding.FrgmentHomeBinding;

/**
 * Generated by generator-android-template
 */
public class FrgmentHome extends FragmentBase<FrgmentHomeBinding, FrgmentHomeVM> {
    @Override
    public int data() {
        return BR.frgmentHome;
    }

    @Override
    public int layoutResources() {
        return R.layout.frgment_home;
    }

    @Override
    public FrgmentHomeVM baseFragmentVM(FrgmentHomeBinding binding, Bundle savedInstanceState) {
        return new FrgmentHomeVM(this, binding);
    }
}
