package <%= appPackage %>.<%= packageName %>;
import android.content.Context;
import com.joxad.easydatabinding.base.BaseVM;

/**
 * Generated by generator-android-template
 * <!!!!!> You have to replace the Object to your POJO class that will be handled in the VM <!!!!!>
 */
public class <%= itemVM %> extends BaseVM<Object>{
    private static final String TAG = <%= itemVM %>.class.getSimpleName();

    /***
      * @param context
      * @param model
      */
     public <%= itemVM %>(Context context, Object model) {
         super(context, model);
     }

     @Override
     public void onCreate() {

     }
}
