package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.activity.ActivityBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
import android.databinding.ObservableArrayList;

import android.os.Bundle;
import android.support.annotation.Nullable;
import me.tatarka.bindingcollectionadapter2.ItemBinding;
/**
 * Generated by generator-android-template
 */
public class <%= name %>VM extends ActivityBaseVM<<%= name %>, <%= name %>Binding> {
  private static final String TAG = <%= name %>VM.class.getSimpleName();

   public ObservableArrayList<<%= itemVM %>> items;
   public ItemBinding<<%= itemVM %>> itemView = ItemBinding.of(BR.<%= itemBR %>, R.layout.<%= itemLayoutXml %>);

  /***
    * @param activity
    * @param binding
    */
   public <%= name %>VM(<%= name %> activity, <%= name %>Binding binding, @Nullable Bundle savedInstance) {
       super(activity, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {
     items = new ObservableArrayList<>();

     loadData();
   }

   /***
    * Load the data from WS or DB to show them in the recycler
   ***/
   public void loadData() {

   }
   /***
    * Add one mode o
   ***/
   private void addVM(<%= itemVM %> vm) {
     items.add(vm);
   }


}
