package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
import android.databinding.ObservableArrayList;

import me.tatarka.bindingcollectionadapter2.ItemBinding;
/**
 * Generated by generator-android-template
 */
public class <%= name %>VM extends FragmentBaseVM<<%= name %>, <%= name %>Binding> {

   public ObservableArrayList<<%= itemVM %>> items;
   public ItemBinding<<%= itemVM %>> itemView = ItemBinding.of(BR.<%= itemBR %>, R.layout.<%= itemLayoutXml %>);

  /***
    * @param activity
    * @param binding
    */
   public <%= name %>VM(<%= name %> activity, <%= name %>Binding binding) {
       super(activity, binding);
   }

   @Override
   public void onCreate() {
     items = new ObservableArrayList<>();
     loadData();
   }

   /***
    * Load the data from WS or DB to show them in the recycler
   ***/
   public void loadData() {

   }
   /***
    * Add one mode o
   ***/
   private void addVM(<%= itemVM %> vm) {
     items.add(vm);
   }


}
