package <%= appPackage %>;

import com.joxad.easydatabinding.fragment.FragmentBase;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
import android.os.Bundle;

/**
 * Generated by generator-android-template
 */
public class <%= name %> extends FragmentBase<<%= name %>Binding, <%= name %>VM> {


    public static <%= name %> newInstance() {
         Bundle args = new Bundle();
         <%= name %> fragment = new <%= name %>();
         fragment.setArguments(args);
         return fragment;
     }

    @Override
    public int data() {
        return BR.<%= BR %>;
    }

    @Override
    public int layoutResources() {
        return R.layout.<%= layoutName %>;
    }

    @Override
    public <%= name %>VM baseFragmentVM(<%= name %>Binding binding, Bundle savedInstanceState) {
        return new <%= name %>VM(this, binding);
    }
}
