package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBase;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
import android.os.Bundle;

/**
 * Generated by generator-android-template
 */
public class <%= name %> extends DialogBottomSheetBase<<%= name %>Binding, <%= name %>VM> {


  public static <%= name %> newInstance() {
       Bundle args = new Bundle();
       <%= name %> fragment = new <%= name %>();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.<%= BR %>VM;
    }

    @Override
    public int layoutResources() {
        return R.layout.<%= layoutName %>;
    }

    @Override
    public <%= name %>VM baseFragmentVM(<%= name %>Binding binding) {
        return new <%= name %>VM(this, binding);
    }


    /**
     * Use this part if you want to put the dialog fullscreen
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        BottomSheetDialog dialog = (BottomSheetDialog) super.onCreateDialog(savedInstanceState);
        dialog.setOnShowListener(dialog1 -> {
            BottomSheetDialog d = (BottomSheetDialog) dialog1;
            FrameLayout bottomSheet = (FrameLayout) d.findViewById(android.support.design.R.id.design_bottom_sheet);
            BottomSheetBehavior<FrameLayout> bot = BottomSheetBehavior.from(bottomSheet);
            bot.setState(BottomSheetBehavior.STATE_EXPANDED);
            bottomSheet.setBackgroundColor(ContextCompat.getColor(getActivity(), android.R.color.transparent));

        });
        return dialog;
    }
    */
}
