package <%= appPackage %>;

import com.joxad.easydatabinding.activity.ActivityBase;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= activityName %>Binding;

/**
 * Generated by generator-android-template
 */
public class <%= activityName %>VM extends ActivityBaseVM<<%= activityName %>, <%= activityName %>Binding> {
  /***
    * @param activity
    * @param binding
    */
   public <%= activityName %>VM(<%= activityName %> activity, <%= activityName %>Binding binding) {
       super(activity, binding);
   }

   @Override
   public void onCreate() {

   }
}
