package <%= appPackage %>;

import com.joxad.easydatabinding.activity.ActivityBase;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;

/**
 * Generated by generator-android-template
 */
public class <%= activityName %> extends ActivityBase<<%= activityName %>Binding, <%= activityName %>VM> {
    @Override
    public int data() {
        return BR.templateActivityVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.template_activity;
    }

    @Override
    public <%= activityName %>VM baseActivityVM(<%= activityName %>Binding binding, Bundle savedInstanceState) {
        return new <%= activityName %>VM(this, binding);
    }
}
