package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.activity.ActivityBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;

import android.os.Bundle;
import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class <%= name %>VM extends ActivityBaseVM<<%= name %>, <%= name %>Binding> {

  private static final String TAG = <%= name %>VM.class.getSimpleName();
  /***
    * @param activity
    * @param binding
    */
   public <%= name %>VM(<%= name %> activity, <%= name %>Binding binding,@Nullable Bundle savedInstance) {
       super(activity, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
