package <%= appPackage %>.<%= packageName %>;

import com.joxad.easydatabinding.activity.ActivityBaseVM;
import <%= appPackage %>.R;
import <%= appPackage %>.BR;
import <%= appPackage %>.databinding.<%= name %>Binding;
/**
 * Generated by generator-android-template
 */
public class <%= name %>VM extends ActivityBaseVM<<%= name %>, <%= name %>Binding> {
  /***
    * @param activity
    * @param binding
    */
   public <%= name %>VM(<%= name %> activity, <%= name %>Binding binding) {
       super(activity, binding);
   }

   @Override
   public void onCreate() {

   }
}
